<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="sensors">
  
  <!-- Lidar Sensor -->
    <link name="lidar_link">
      <visual>
        <geometry>
          <cylinder radius="0.07" length="0.05"/>
        </geometry>
        <material name="Gazebo/Red">
          <color rgba="1.0 0.0 0.0 1.0"/>
        </material>
      </visual>
    </link>
    
    <joint name="lidar_joint" type="fixed">
      <parent link="base_link"/>
      <child link="lidar_link"/>
      <origin xyz="0 0 ${body_height/2 + 0.025}"/>
    </joint>
    
    
  <!-- IMU Sensor -->
    <link name="imu_link">
      <pose>0.0 0.0 0.0 0 0 0</pose>
      <visual>
        <geometry>
          <box size="0.03 0.03 0.01"/>
        </geometry>
        <material name="green">
          <color rgba="0.0 1.0 0.0 1.0"/>
        </material>
      </visual>
    </link>
    <joint name="imu_joint" type="fixed">
      <parent link="base_link"/>
      <child link="imu_link"/>
      <origin xyz="0.0 0.0 0.0"/>
    </joint> 


  <!--    GPS Sensor     -->
    <link name="pole_link">
      <visual>
        <geometry>
          <cylinder radius="0.01" length="0.4"/>
        </geometry>
        <material name="red">
          <color rgba="1.0 0.0 0.0 1.0"/>
        </material>
      </visual>
    </link>
      
    <joint name="pole_joint" type="fixed">
      <parent link="base_link"/>
      <child link="pole_link"/>
      <origin xyz="-0.3 0.0 ${body_height/2 + 0.2}"/>
    </joint>
     
    <link name="gps_link">
      <visual>
        <geometry>
          <box size="0.05 0.05 0.05"/>
        </geometry>
        <material name="blue">
          <color rgba="0.0 0.0 1.0 1.0"/>
        </material>
      </visual>
    </link>
    
    <joint name="gps_joint" type="fixed">
      <parent link="pole_link"/>
      <child link="gps_link"/>
      <origin xyz="0.0 0.0 ${0.2+0.025}"/>
    </joint> 
    

  <!-- Camera Sensor -->
    <link name="camera_link">
      <visual>
        <geometry>
          <box size="0.04 0.05 0.05"/>
        </geometry>
        <material name="gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      
    </link>
    <joint name="camera_joint" type="fixed">
      <parent link="base_link"/>
      <child link="camera_link"/>
      <origin xyz="${body_length/2+0.04/2} 0.0 0.0"/>
    </joint>
    
  </xacro:macro>


</robot>

